[tool.poetry]
name = "pbl4-ORC"
version = "0.1.0"
description = ""
authors = ["vohoanglong01072001 <mamlong34@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
scipy = "^1.7.1"
PyYAML = "^6.0"
scikit-image = "^0.18.3"
torch = "^1.10.0"
torchvision = "^0.11.1"
opencv-python-headless = "^4.5.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.10b0"
flake8 = "^4.0.1"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
